Overlapping shifts #132
oss-slu/shelter_volunteers pull request #135
Opened 2024-10-14 20:36 UTC by amalrzv

Fixes #132 

**What was changed?**
Implemented an overlapping shifts section that indicates whether shifts overlap in the Shelters.js file

*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*

Changes the shift sign up part where you implement 

**Why was it changed?**
Need to indicate when the shifts are overlapping immediately informing the volunteer

*Here, describe the issue that you are fixing with this code, and why your code fixes it.*

The shifts that overlap need to be marked with an X, which wasn't previously done. The shift times are compared to indicate with a check mark or an x if a shift overlaps. 

**How was it changed?**

*Here, get into detail about what files you modified, and talk about the most important lines in regards to fixing the issue.*

The Shelters.js file holds the logic regarding the shifts. I checked the overlap by checking if the shift starts before the selected shift has ended and checking if the shift ends after the the other selected shift has started. The logic for the submit button that is disabled  occurs when the shifts overlap (presenting an alert) otherwise the submit button is enabled. 

**Screenshots that show the changes (if applicable):**

<img width="705" alt="Screenshot 2024-10-14 at 12 06 22 PM" src="https://github.com/user-attachments/assets/d3a40a35-0c75-4710-926d-ffa8cf718e1c">

2024-10-14 22:38 UTC, cbiddle3 reviewed
Already discussed in class but moving this logic to the current selection part of the website

2024-10-14 22:42 UTC, cbiddle3 commented on client_app/src/components/volunteer/ConfirmationPage.js
> +  return otherShifts.some(otherShift => {
you should be able to just directly compare the shift.start_time and shift.end_time

2024-10-14 22:42 UTC, cbiddle3 commented on client_app/src/components/volunteer/ConfirmationPage.js
> +                    <IconButton>
Discussed in class with error message and tooltip

2024-10-14 23:44 UTC, cbiddle3 requested changes
Just make the changes above moving logic to current selection

2024-10-21 05:33 UTC, Brijitha1609 reviewed
Great job! To further enhance the user experience, it might be helpful to include a visual indication, such as an icon (like an "X"), to alert users when overlapping shifts have been selected. This additional feedback can guide users in making more informed selections.

2024-10-22 01:06 UTC, Brijitha1609 approved these changes
Great job implementing the overlap detection functionality and ensuring that it works as expected. You've provided clear visual feedback to the user when overlapping shifts are detected, which is essential for usability. The approach you've taken to manage overlapping shifts is logical and well-structured.

2024-10-22 01:08 UTC, merged